version: 0.2

env:
  variables:
    HURL_VERSION: "6.0.0"
    HURL: "./target/release/hurl-installation"
    HURL_DIR: "./hurl"

phases:
  install:
    commands:
      - "dnf install -y pkg-config gcc openssl-devel libxml2-devel"
      - "curl https://sh.rustup.rs -sSf | sh -s -- -y"
      - "source $HOME/.cargo/env"
      - "rustc --version"
      - "cargo --version"
      - "cargo install hurl"
  build:
    commands:
      - "echo ## Test Crm Connection..."
      - "hurl --test --verbose --variable crm_url=$CRM_URL ${CODEBUILD_SRC_DIR}/${HURL_DIR}/healthcheck.hurl"
