#!/bin/bash

export NEXT_PUBLIC_CRM_URL="https://$CRM_URL"
export NEXT_PUBLIC_LOCALHOST="$CRM_URL"
export NEXT_PUBLIC_FALLBACK_LANGUAGE="en"
export NEXT_PUBLIC_GRAPHQL_API_URL="https://$CRM_URL/api/graphql"
export NEXT_PUBLIC_API_URL="https://yourserver.io/api/"
export NEXT_PUBLIC_VILNACRM_GMAIL="info@app.vilnacrm.com"
export MEMLAB_CRM_URL="https://$CRM_URL"
export NEXT_PUBLIC_CONTINUOUS_DEPLOYMENT_HEADER_NAME="$CLOUDFRONT_HEADER"
export NEXT_PUBLIC_CONTINUOUS_DEPLOYMENT_HEADER_VALUE="$CLOUDFRONT_HEADER"

CRM_GIT_REPOSITORY_LAST_COMMIT_SHA=$(git rev-parse HEAD)
export CRM_GIT_REPOSITORY_LAST_COMMIT_SHA

CRM_GIT_REPOSITORY_LAST_COMMIT_NAME=$(git log --format=%B -n 1 | cat | head -n 1)
export CRM_GIT_REPOSITORY_LAST_COMMIT_NAME

CRM_GIT_REPOSITORY_LAST_COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
export CRM_GIT_REPOSITORY_LAST_COMMIT_AUTHOR