name: Trigger AWS CI-CD-Infra CodePipeline

on:
  push:
    branches-ignore:
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

permissions:
  id-token: write
  contents: read

jobs:
  trigger-pipeline:
    name: Trigger AWS CodePipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{vars.TEST_AWS_ACCOUNT_ID}}:role/ci-cd-infra-crm-trigger-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Trigger CodePipeline
        run: |
          aws codepipeline start-pipeline-execution --name ci-cd-infra-crm-test-pipeline
